### ISSUE TITLE
Error: Cannot find module './communications'

### ISSUE THREAD

**Issue by FelixLusseau** [AndreVarandas/clash-royale-api#96]
Hi ! 
I have an issue with the clash-royale-api module.

**Describe the bug**
Since the upgrade from v1.1.13, the `npm install` are failling and the Discord bot is not able to start anymore.
Many files have disappeared from the `lib` folder of the module.

**To Reproduce**
Following the Readme

**Error message**
```
node:internal/modules/cjs/loader:1189
  throw err;
  ^

Error: Cannot find module './communications'
Require stack:
- ./node_modules/@varandas/clash-royale-api/lib/index.js
- ./bot.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1186:15)
    at Module._load (node:internal/modules/cjs/loader:1012:27)
    at Module.require (node:internal/modules/cjs/loader:1271:19)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (./node_modules/@varandas/clash-royale-api/lib/index.js:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Module._load (node:internal/modules/cjs/loader:1065:12)
    at Module.require (node:internal/modules/cjs/loader:1271:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    './node_modules/@varandas/clash-royale-api/lib/index.js',
    './bot.js'
  ]
}

Node.js v22.2.0
```

Thanks for your help

**Comment by AndreVarandas** [comment]
Hi @FelixLusseau  there is indeed an issue with the build and release of the library. I will take a look once I find a few mins to work on this. Thank you for raising the issue.

**Comment by AndreVarandas** [comment]
Should be fixed with version 1.1.17, could you give it a try?

**Comment by FelixLusseau** [comment]
Hi @AndreVarandas !

Thank you very much all is okay now 😄

I was stuck and more reluctant to run `npm i` without preparing a backup of the old package so I became late on some updates due to this...

Thank you for this wrapper of the Official API too

**Comment by AndreVarandas** [comment]
Thank you for your help and interest in the wrapper @FelixLusseau! I'm now closing the issue, build something great! :)
